INSERT INTO tb_category (name) VALUES ('Mobile Compatible');      -- ID: 1
INSERT INTO tb_category (name) VALUES ('Air-Gapped Wallets');     -- ID: 2
INSERT INTO tb_category (name) VALUES ('Multi-currency');         -- ID: 3
INSERT INTO tb_category (name) VALUES ('Open Source Firmware');   -- ID: 4
INSERT INTO tb_category (name) VALUES ('Bitcoin Only');           -- ID: 5
INSERT INTO tb_category (name) VALUES ('DIY');                    -- ID: 6
INSERT INTO tb_category (name) VALUES ('Carteira Biométrica');    -- ID: 7

INSERT INTO tb_brand (name) VALUES ('Ledger');
INSERT INTO tb_brand (name) VALUES ('ColdCard');
INSERT INTO tb_brand (name) VALUES ('Trezor');
INSERT INTO tb_brand (name) VALUES ('Specter');
INSERT INTO tb_brand (name) VALUES ('BlockStream');
INSERT INTO tb_brand (name) VALUES ('Shift Crypto');
INSERT INTO tb_brand (name) VALUES ('KeepKey');
INSERT INTO tb_brand (name) VALUES ('CoolBitX');
INSERT INTO tb_brand (name) VALUES ('SecuX');
INSERT INTO tb_brand (name) VALUES ('Ellipal');
INSERT INTO tb_brand (name) VALUES ('SafePal');
INSERT INTO tb_brand (name) VALUES ('D''CENT');
INSERT INTO tb_brand (name) VALUES ('Keystone');
INSERT INTO tb_brand (name) VALUES ('Ngrave');
INSERT INTO tb_brand (name) VALUES ('Tangem');

INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Ledger Flex', 'A Ledger Flex é uma carteira de hardware compacta e flexível desenvolvida pela Ledger, projetada para armazenar criptomoedas de maneira segura com tela OLED e conectividade Bluetooth.', 1450.00, 'img/Ledger-flex-card.png','img/Ledger-flex-img2.png', 'img/Ledger-flex-img3.png', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 1, 1);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('ColdCard Mk4', 'A Coldcard MK4 é uma carteira de hardware focada em segurança, com tela colorida, autenticação de dois fatores e suporte para assinaturas multissig.', 1900.00, 'img/Coldcard-mk4-card.png','img/Coldcard-mk4-img2.png', 'img/Coldcard-mk4-img3.png', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 2, 2);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Trezor Model T', 'A Trezor Model T é uma carteira de hardware com tela touchscreen colorida, backup e recuperação com semente de 12-24 palavras, e autenticação de dois fatores.', 1600.00, 'public/img/Trezor-t-card.png','public/img/Ledger-flex-img2.png', 'public/img/Ledger-flex-img3.png', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 3, 3);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Trezor Safe 3', 'A Trezor Safe 3 é uma carteira de hardware segura, com autenticação multifatorial e backup criptografado, garantindo proteção das chaves privadas.', 899.00, 'img/Trezor-safe3-card.png', 'img/Trezor-safe3-img2.png', 'img/Trezor-safe3-img3.png','Tipo-c', '9 cm x 7.4 cm x 6 cm', 3, 3);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Ledger Nano', 'A Ledger Nano é uma carteira de hardware com chip seguro de nível militar e autenticação multifator para proteger suas criptomoedas contra ameaças digitais.', 599.00, 'img/Ledger-nano-card.png','img/Ledger-nano-img2.png', 'img/Ledger-nano-img3.png', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 1, 1);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Trezor Safe 5', 'O Trezor Safe 5 é uma carteira de hardware com tecnologia avançada e design intuitivo para proteger ativos digitais com segurança de ponta.', 1299.00, 'img/Trezor-safe5-card.png', 'img/Trezor-safe5-img2.png', 'img/Trezor-safe5-img3.png','Tipo-c', '9 cm x 7.4 cm x 6 cm', 3, 3);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Specter v0.1', 'A Specter DIY é uma carteira de hardware com código-fonte aberto, permitindo a verificação e modificação do firmware pelos usuários para maior segurança.', 499.00, 'img/Specter-card.png', 'img/Specter-img2.png', 'img/Specter-img3.png','Tipo-c', '9 cm x 7.4 cm x 6 cm', 6, 4);
INSERT INTO tb_product (name, description, price, img,img2,img3, conection_type, size, category_id, brand_id) VALUES ('Jade', 'O Blockstream Jade é uma carteira de hardware para proteger fundos contra ataques cibernéticos, permitindo a assinatura segura de transações com chaves privadas protegidas.', 499.00, 'img/Jade-card.png', 'img/Jade-img2.png', 'img/Jade-img3.png','Tipo-c', '9 cm x 7.4 cm x 6 cm', 5, 5);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('BitBox02', 'A BitBox02 é uma carteira de hardware suíça com foco em segurança e simplicidade, possuindo firmware open‑source e autenticação multifatorial.', 950.00, 'https://privacypros.io/images/landing-pages/bitbox02-multi/bitbox02-multi.png', 'https://99bitcoins.com/wp-content/uploads/2021/04/BitBox02-in-hand.jpg', 'https://99bitcoins.com/wp-content/uploads/2021/04/BitBox02-box-contents.jpg', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 4, 6);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('KeepKey', 'A KeepKey é uma carteira de hardware com design robusto e tela grande, oferecendo suporte a várias criptomoedas e backup seguro com frases mnemônicas.', 750.00, 'https://i0.wp.com/www.walletmart.io/wp-content/uploads/2018/11/Keepkey1.png?fit=500%2C500&ssl=1', 'https://thecryptomerchant.com/cdn/shop/products/s-l1600_3_1024x1024.jpg', 'https://thecryptomerchant.com/cdn/shop/products/s-l1600_4_1024x1024.jpg', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 3, 7);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('CoolWallet Pro', 'A CoolWallet Pro é uma carteira de hardware ultrafina com conectividade Bluetooth e resistente à água, ideal para uso diário e integração com DeFi.', 1120.00, 'https://398ef508.delivery.rocketcdn.me/wp-content/uploads/2023/06/coolwalletpro.png', 'https://blockonomi.com/wp-content/uploads/2021/05/coolwallet-pro-review-2.jpeg', 'https://everybithelps.co.uk/wp-content/uploads/2021/05/unboxing-the-cool-wallet-pro.png', 'Bluetooth', '85.6 mm x 53.98 mm x 0.8 mm', 1, 8);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('SecuX V20', 'A SecuX V20 é uma carteira de hardware com tela touchscreen colorida e suporte para múltiplas criptomoedas, combinando segurança e facilidade de uso.', 980.00, 'https://images.prismic.io/btcdirect-shop/Z4puNZbqstJ99k28_secuxv20side.png?auto=format%2Ccompress&rect=88%2C94%2C403%2C403&w=586&h=586', 'https://tse4.mm.bing.net/th/id/OIP.MO8xuPQ4tEDuWolpvqmsUQHaHa?pid=Api', 'https://tse1.mm.bing.net/th/id/OIP.G4hoaJ8mXdZ_1xr4Gx_epwHaHa?pid=Api', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 3, 9);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('Ellipal Titan', 'A Ellipal Titan é uma carteira de hardware completamente air‑gapped, com corpo metálico e autenticação via QR Code, focada em máxima segurança offline.', 1420.00, 'https://www.ellipal.com/cdn/shop/files/mega-manu-Titan-2.png?v=1750399568&width=210', 'https://shop.bitcoinaus.com.au/cdn/shop/products/ellipal-titan-cold-wallet-2.jpg', 'https://shop.bitcoinaus.com.au/cdn/shop/products/ellipal-titan-cold-wallet-4.jpg', 'QR Code', '118 mm x 66 mm x 9.7 mm', 2, 10);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('SafePal S1', 'A SafePal S1 é uma carteira de hardware portátil e acessível com autenticação via QR Code e suporte para DeFi e NFTs.', 620.00, 'https://www.safepal.com/assets/img/header/icon_s1.png', 'https://www.gemini.com/cryptopedia/media/safepal-wallet-hardware-cryptopedia.png', 'https://coingape.com/wp-content/uploads/2021/03/1615552399650.png', 'QR Code', '88 mm x 52 mm x 6 mm', 1, 11);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('D CENT', 'A D’CENT Biometric é uma carteira de hardware com leitor de impressão digital integrado, oferecendo autenticação biométrica e suporte a múltiplas moedas.', 870.00, 'https://store.dcentwallet.com/cdn/shop/files/Bio_Front_95250b04-0d54-4535-bc0d-2d61774e94e2_2_533x.webp?v=1736123017', 'https://coincierge.de/wp-content/uploads/2022/02/dcent-biometric-wallet-display.jpg', 'https://coincierge.de/wp-content/uploads/2022/02/dcent-wallet-box.jpg', 'Tipo-c', '9 cm x 7.4 cm x 6 cm', 7, 12);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('Keystone Pro', 'A Keystone Pro é uma carteira de hardware air‑gapped com autenticação via QR Code e tela touchscreen, ideal para máxima segurança de ativos digitais.', 1320.00, 'https://www.thecryptomerchantsa.com/cdn/shop/files/Keystone3Pro1.png?v=1737470917', 'https://bitcoin-news.de/wp-content/uploads/2022/10/Keystone-3-Pro-Vorderseite.png', 'https://bitcoin-news.de/wp-content/uploads/2022/10/Keystone-3-Pro-Display-mit-QR-Code.png', 'QR Code', '112 mm x 65 mm x 13 mm', 2, 13);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('NGRAVE ZERO', 'A NGRAVE ZERO é uma carteira de hardware ultra segura, certificada EAL7, totalmente offline e com display touchscreen para máxima proteção.', 1899.00, 'https://a.storyblok.com/f/126258/996x840/cdfbb46db0/zero-2.png/m/777x655/filters:quality(100)', 'https://coinsutra.com/wp-content/uploads/2022/11/Ngrave-ZERO.jpeg', 'https://coinsutra.com/wp-content/uploads/2022/11/What-is-in-the-box.jpeg', 'QR Code', '125 mm x 72 mm x 10 mm', 2, 14);
INSERT INTO tb_product (name, description, price, img, img2, img3, conection_type, size, category_id, brand_id) VALUES ('Tangem Wallet', 'A Tangem Wallet é uma solução inovadora de hardware em formato de cartão NFC, permitindo armazenar chaves privadas com facilidade de uso e portabilidade.', 370.00, 'https://res.cloudinary.com/etherbit/image/upload/f_auto,q_auto:eco,c_limit,w_450/s/build/img/products/1x1-f88904-etherbit-tangem-wallet.png', 'https://blockonomi.com/wp-content/uploads/2022/11/tangem-wallet-review.jpeg', 'https://assets-global.website-files.com/6211442c45305b51a4b41443/643d540212354c_tangem-wallet-review.png', 'NFC', '85.6 mm x 53.98 mm x 0.8 mm', 1, 15);

INSERT INTO tb_user (first_name, last_name, email, password, cpf) VALUES ('Teste', 'testesobre', 'teste@example.com', '$2a$10$RyGlTLJf3E3h6bpaMqt9aeAKEdivsRjoCvwFHrMRWLngta4S87gIO', '123.456.789-00');
INSERT INTO tb_user (first_name, last_name, email, password, cpf) VALUES ('testfirst', 'testlast', 'teste@gmail.com', '$2a$10$RyGlTLJf3E3h6bpaMqt9aeAKEdivsRjoCvwFHrMRWLngta4S87gIO', '123.456.789-00');

INSERT INTO tb_address (street, number, cep, city, user_id) VALUES ('Rua das Flores', '123', '12345-678', 'São Paulo', 1);
INSERT INTO tb_address (street, number, cep, city, user_id) VALUES ('Avenida Paulista', '456', '98765-432', 'São Paulo', 2);